In [1]:
#!/usr/bin/env python
import git
import sys
import datetime
from pathlib import Path
sys.path.append('/home/bij/Projects/fdtd/')
import math
import time
import fdtd
import fdtd.backend as bd
import matplotlib.pyplot as plt
import numpy as np
import random
import torch
import torch.optim as optim
import torchvision
from torchvision.utils import save_image
from torch.utils.tensorboard import SummaryWriter
from PIL import Image
import scipy
from autoencoder import AutoEncoder
import argparse
from os import listdir
from os.path import isfile, join
import util
from matplotlib.backends.backend_agg import FigureCanvasAgg
from matplotlib.figure import Figure

parser = argparse.ArgumentParser(description='Process args.')
parser.add_argument('-f', '--load-file', type=str, default=None,
                    help='File to load params from before training starts. Overrides --load-step.')
parser.add_argument('-l', '--load-step', type=str, default='0',
                    help='Where to start training. If latest, will start at the latest checkpoint.')
parser.add_argument('-s', '--save-steps', type=int, default='1000',
                    help='How often to save the model.')
parser.add_argument('-c', '--coverage-ratio', type=float, default=1.0,
                    help='How much distance a wave can cover as a proportion of the diagonal length of the sim.')
parser.add_argument('-m', '--max-steps', type=int, default='1000000000000000',
                    help='How many steps to train.')
parser.add_argument('-d', '--dry-run', type=bool, default=False,
                    help='If true, does not save model checkpoint.')
parser.add_argument('-rog', '--reset-grid-optim', default=False, action='store_true',
                    help='If true, loads completely new params for the grid and optimizer.')
parser.add_argument('-is', '--image-size', type=int, default=40,
                    help='Size of each side of the image. Determines grid size.')
parser.add_argument('-sc', '--image-scaler', type=int, default=1,
                    help='How much to scale the entire simulation by (changes the dimensions of the model).')
parser.add_argument('-oc', '--old-scaler', type=int, default=1,
                    help='If the loaded file was scaled, that scaler value.')
parser.add_argument('-bem', '--bypass-em', default=False, action='store_true',
                    help='If set, will disable the EM component of the model.')
parser.add_argument('-gray', '--grayscale', default=False, action='store_true',
                    help='If set, will force the input and output images to be grayscale.')
parser.add_argument('-thw', '--target-half-way', default=False, action='store_true',
                    help='If set, will only produce loss for the timestep halfway up the coverage ratio.')
parser.add_argument('-sds', '--source-down-scaler', type=int, default=1, 
                    help='How much to stride sources in the cortical substrate.')
parser.add_argument('-sgd', '--use-sgd', default=False, action='store_true',
                    help='If set, will switch to SGD instead of Adam. Useful for finetuning.')
parser.add_argument('-ti', '--target-img', default=None, action='store_true',
                    help='If set, will only process this image file.')
args = parser.parse_args()

args.load_file = 'model_checkpoints/stability-improvements/md_000000037800.pt'
args.grayscale = True
#args.image_scaler = 4
args.image_scaler = 5

def get_sorted_paths(directory_list, target_ext='.png'):
    path_list = []
    for directory in directory_list:
        paths = [join(directory,f) for f in listdir(directory) if isfile(join(directory, f)) and f.endswith(target_ext)]
        print(f'Found {len(paths)} files in {directory}')
        path_list += paths
    path_list.sort()
    return path_list

def scale_img(img, s=2):
    return torchvision.transforms.functional.resize(img, size=(img.shape[-2] * s, img.shape[-1] * s), interpolation=torchvision.transforms.InterpolationMode.NEAREST)

#img_paths = get_sorted_paths(['./optical_illusions/'])
img_paths = [#'./optical_illusions/robinson_1.png',
             #'./optical_illusions/robinson_2.png',
    './optical_illusions/robinson_3.png',
     #'./optical_illusions/Cornsweet_illusion.png',
     #'./optical_illusions/Ehrenstein_Illusion.png',
     #'./optical_illusions/dots_Brightness-Optical-Illusion.png',
     #'./optical_illusions/illusory_brigntness.png',
     #'./optical_illusions/illusory_brigntness_reverse.png',
     #'./optical_illusions/rectangle_Brightness-Optical-Illusion2.png'
            ]

# ## Set Backend
backend_name = "torch"
fdtd.set_backend(backend_name)
if(backend_name.startswith("torch.cuda")):
    device = "cuda"
else:
    device = "cpu"

In [2]:
img_paths

['./optical_illusions/robinson_3.png']

In [3]:
image_transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Resize((args.image_size*args.image_scaler, args.image_size*args.image_scaler))])

img_file = img_paths[0]
print(img_file.split('/')[-1].split('.')[0])
img = Image.open(img_file)
print('Image shape: ', np.array(img).shape)
img = image_transform(img)[None, ...]
if(args.grayscale):
    img = torchvision.transforms.Grayscale()(img)[None, 0, ...]
else:
    img = torchvision.transforms.Grayscale()(img)
print('Image shape: ', img.shape)
ih, iw = tuple(img.shape[2:4])
#ih, iw = img.shape[2]*4, img.shape[3]*4
print('ih, iw: ', ih, iw)

# Physics constants
WAVELENGTH = 1550e-9 # meters
SPEED_LIGHT: float = 299_792_458.0  # [m/s] speed of light
GRID_SPACING = 0.1 * WAVELENGTH # meters



# Size of grid boundary layer
bw = 10*args.image_scaler
# Create FDTD Grid
grid_h, grid_w = (ih+bw*2, iw+bw*2)
print('Grid height and width: ', grid_h, grid_w)
# Boundaries with width bw
grid = fdtd.Grid(
    (grid_h, grid_w, 1),
    grid_spacing=GRID_SPACING,
    permittivity=1.0,
    permeability=1.0,
)

# Calculate how long it takes a wave to cross the entire grid.
grid_diag_cells = math.sqrt(grid_h**2 + grid_w**2)
grid_diag_len = grid_diag_cells * GRID_SPACING
grid_diag_steps = int(grid_diag_len/SPEED_LIGHT/grid.time_step)+1
print('Time steps to cover entire grid: ', grid_diag_steps)
# The number of steps is based on the coverage ratio.
if(args.target_half_way):
    em_steps = int(grid_diag_steps*args.coverage_ratio/2)
else:
    em_steps = int(grid_diag_steps*args.coverage_ratio)
print('Time steps the grid will run for: ', em_steps)


# Create learnable objects at the boundaries
grid[  0: bw, :, :] = fdtd.LearnableAnisotropicObject(permittivity=2.5, name="xlow", device=device)
grid[-bw:   , :, :] = fdtd.LearnableAnisotropicObject(permittivity=2.5, name="xhigh", device=device)
grid[:,   0:bw, :] = fdtd.LearnableAnisotropicObject(permittivity=2.5, name="ylow", device=device)
grid[:, -bw:  , :] = fdtd.LearnableAnisotropicObject(permittivity=2.5, name="yhigh", device=device)
grid[:, :, 0] = fdtd.PeriodicBoundary(name="zbounds")

# Creat the cortical column sources
grid[bw:bw+ih,bw:bw+iw,0] = fdtd.CorticalColumnPlaneSource(
    period = WAVELENGTH / SPEED_LIGHT,
    polarization = 'x', # BS value, polarization is not used.
    name = 'cc',
    source_stride = args.source_down_scaler,
)

# Object defining the cortical column substrate 
grid[bw:-bw, bw:-bw, :] = fdtd.LearnableAnisotropicObject(permittivity=2.5, is_substrate=True, name="cc_substrate", device=device)

torch.autograd.set_detect_anomaly(True)
# The weights for the reconstruction loss at each em time step. 
loss_step_weights = torch.ones(em_steps, device=device)/em_steps
#loss_step_weights = torch.nn.Parameter(torch.reshape(loss_step_weights, (-1, 1, 1, 1, 1)))
loss_step_weights.requires_grad = True
softmax = torch.nn.Softmax(dim=0)

# Initialize the model and grid with default params.
if(args.grayscale):
    chans = 1
else:
    chans = 3
model = AutoEncoder(num_em_steps=em_steps, grid=grid, input_chans=chans, output_chans=chans, source_stride=args.source_down_scaler, bypass_em=args.bypass_em).to(device)
print('All grid objects: ', [obj.name for obj in grid.objects])
grid_params_to_learn = []
grid_params_to_learn += [util.get_object_by_name(grid, 'xlow').inverse_permittivity]
grid_params_to_learn += [util.get_object_by_name(grid, 'xhigh').inverse_permittivity]
grid_params_to_learn += [util.get_object_by_name(grid, 'ylow').inverse_permittivity]
grid_params_to_learn += [util.get_object_by_name(grid, 'yhigh').inverse_permittivity]
grid_params_to_learn += [util.get_object_by_name(grid, 'cc_substrate').inverse_permittivity]
# Nonlinearity weights for the substrate. 
grid_params_to_learn += [util.get_object_by_name(grid, 'cc_substrate').nonlin_conv.weight]
grid_params_to_learn += [util.get_object_by_name(grid, 'cc_substrate').nonlin_conv.bias]
# Nonlinearity weights for the cortical columns. 
grid_params_to_learn += [util.get_source_by_name(grid, 'cc').nonlin_conv.weight]
grid_params_to_learn += [util.get_source_by_name(grid, 'cc').nonlin_conv.bias]
# The weights for the loss.
grid_params_to_learn += [loss_step_weights]

# Load saved params for model and optimizer.
#checkpoint_steps = [int(cf.split('_')[-1].split('.')[0]) for cf in checkpoints]
if(args.load_file is not None):
    start_step = int(args.load_file.split('/')[-1].split('_')[-1].split('.')[0])
    print('Loading model {0}. Starting at step {1}.'.format(args.load_file, start_step))
    optimizer_path = args.load_file.rsplit('.', 1)[0] + '.opt'
    grid_path = args.load_file.rsplit('.', 1)[0] + '.grd'
    model.load_state_dict(torch.load(args.load_file))
else:
    if(args.load_step == 'latest'):
        if(len(checkpoint_steps) > 0):
            latest_idx = np.argmax(checkpoint_steps)
            start_step = checkpoint_steps[latest_idx]
            model_dict_path = model_checkpoint_dir + checkpoints[latest_idx]
            optimizer_path = model_dict_path.rsplit('.', 1)[0] + '.opt'
            grid_path = model_dict_path.rsplit('.', 1)[0] + '.grd'
            print('Loading model {0} with optimizer {1} and grid {2}.'.format(model_dict_path, optimizer_path, grid_path))
            model.load_state_dict(torch.load(model_dict_path))
        else:
            start_step = 0
    elif(int(args.load_step) != 0):
        if(int(args.load_step) not in checkpoint_steps):
            print('Checkpoint {0} not found in {1}'.format(args.load_step, model_checkpoint_dir))
            sys.exit()
        start_step = int(args.load_step)
        model_idx = np.where(np.array(checkpoint_steps) == start_step)[0][0]
        model_dict_path = model_checkpoint_dir + checkpoints[model_idx]
        optimizer_path = model_dict_path.rsplit('.', 1)[0] + '.opt'
        grid_path = model_dict_path.rsplit('.', 1)[0] + '.grd'
        print('Loading model {0} with optimizer {1} and grid {2}.'.format(model_dict_path, optimizer_path, grid_path))
        model.load_state_dict(torch.load(model_dict_path))
    else:
        print('Starting model at step 0')
        start_step = 0
        optimizer_path = None
        grid_path = None

reset_optimizer = False
if((grid_path is not None) and (not args.reset_grid_optim)):
    print('Loading grid params...')
    with torch.no_grad():
        load_grid_params_to_learn = torch.load(grid_path)
        for idx, tensor in enumerate(load_grid_params_to_learn):
            if(tensor.shape == grid_params_to_learn[idx][...].shape):
                grid_params_to_learn[idx][...] = tensor[...]
            else:
                if(idx == len(load_grid_params_to_learn) - 1):
                    tensor = torch.squeeze(tensor)
                # Interpolate the thing....
                print('INFO: Shapes are mismatched: {0} vs {1}'.format(tensor[...].shape, grid_params_to_learn[idx][...].shape))
                
                # If this is a grid param, expand it over the spatial dims.
                if(len(tensor.shape) > 1):
                    reps = np.ones(len(tensor.shape), dtype=int)
                    for i in range(len(reps)):
                        reps[i] = int(args.image_scaler / args.old_scaler)
                        if(i >= 1):
                            break

                    #tensor_np_interp = scipy.ndimage.zoom(tensor.detach().numpy(), reps, order=1)
                    #grid_params_to_learn[idx][...] = torch.from_numpy(tensor_np_interp)
                    #print('INFO: Grid object scaled to shape: ', grid_params_to_learn[idx][...].shape)
                    print('INFO: Grid object NOT scaled to shape: ', grid_params_to_learn[idx][...].shape)
                # If this is the loss step weights, scale it linearly to fit the new size.
                else:
                    tensor_interp = torch.nn.functional.interpolate(tensor[None, None, ...], grid_params_to_learn[idx][...].shape, mode='linear')
                    grid_params_to_learn[idx][...] = tensor_interp
                    print('INFO: EM Step loss object scaled to shape: ', grid_params_to_learn[idx][...].shape)
                    print('EM Steps: ', em_steps)
                    print('Loss step weights: ', loss_step_weights.shape)

                # Since parameter shapes have changed, the optimizer weights are obsolete.
                reset_optimizer = True

# Combine grid and model params and register them with the optimizer.
params_to_learn = [*model.parameters()] + grid_params_to_learn

mse = torch.nn.MSELoss(reduce=False)
loss_fn = torch.nn.MSELoss()

grid.H.requires_grad = True
grid.H.retain_grad()
grid.E.requires_grad = True
grid.E.retain_grad()



robinson_3
Image shape:  (1056, 1056, 3)
Image shape:  torch.Size([1, 1, 200, 200])
ih, iw:  200 200
Grid height and width:  300 300
Time steps to cover entire grid:  607
Time steps the grid will run for:  607
All grid objects:  ['xlow', 'xhigh', 'ylow', 'yhigh', 'cc_substrate']
Loading model model_checkpoints/stability-improvements/md_000000037800.pt. Starting at step 37800.
Loading grid params...
INFO: Shapes are mismatched: torch.Size([40, 240, 1, 3, 3]) vs torch.Size([50, 300, 1, 3, 3])
INFO: Grid object NOT scaled to shape:  torch.Size([50, 300, 1, 3, 3])
INFO: Shapes are mismatched: torch.Size([40, 240, 1, 3, 3]) vs torch.Size([50, 300, 1, 3, 3])
INFO: Grid object NOT scaled to shape:  torch.Size([50, 300, 1, 3, 3])
INFO: Shapes are mismatched: torch.Size([240, 40, 1, 3, 3]) vs torch.Size([300, 50, 1, 3, 3])
INFO: Grid object NOT scaled to shape:  torch.Size([300, 50, 1, 3, 3])
INFO: Shapes are mismatched: torch.Size([240, 40, 1, 3, 3]) vs torch.Size([300, 50, 1, 3, 3])
INFO: Gri

/home/bij/anaconda3/envs/Torch/lib/python3.10/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))


In [25]:
#old_weight = model.conv_linear.weight
#model.conv_linear.weight = torch.nn.Parameter(torch.roll(model.conv_linear.weight, shifts=-1))
#model.conv_linear.weight = torch.nn.Parameter(torch.roll(old_weight, shifts=3))
#model.conv_linear.weight = torch.nn.Parameter(torch.Tensor(np.array([0,0,0,0,1,0]))[None, :, None, None])
#model.conv_linear.weight = old_weight
#model.conv_linear.weight
#old_weight.shape

In [29]:
# Get sample from training data
em_step_loss_weight_dist = softmax(loss_step_weights)
argmax_step = torch.argmax(torch.squeeze(loss_step_weights))

# Only process one image if this is set
if(args.target_img):
    img_paths = [args.target_img]

for img_file in img_paths:
    # Reset the grid
    grid.reset()
    # Load an image
    img_name = img_file.split('/')[-1].split('.')[0]
    print('Processing: ', img_name)
    img = Image.open(img_file)
    img = image_transform(img)[None, ...]
    if(args.grayscale):
        img = torchvision.transforms.Grayscale()(img)[None, 0, ...]
    else:
        img = torchvision.transforms.Grayscale()(img)
    
    # Get the path of the test strip
    illusion_path, illusion_filename = img_file.rsplit('/', 1)
    test_strip_pref = illusion_path + '/test_strips/' + illusion_filename.split('.')[0]
    test_strip_file_a = test_strip_pref + '_teststrip_part_a.png'
    test_strip_file_b = test_strip_pref + '_teststrip_part_b.png'
    print('Opening image {0} with test strip file {1}'.format(img_file, test_strip_file_a))
    
    try:
        test_strip_img_a = np.array(Image.open(test_strip_file_a))
    except:
        print('Could not find {0}, skipping'.format(test_strip_file_a))
        continue
    try:
        test_strip_img_b = np.array(Image.open(test_strip_file_b))
    except:
        print('Could not find {0}, making zeros.'.format(test_strip_file_b))
        test_strip_img_b = np.zeros_like(test_strip_img_a)
    # Make sure it is binary.
    assert np.sum(((test_strip_img_a > 0) * (test_strip_img_a < 1)).astype(np.int)) <= 0
    assert np.sum(((test_strip_img_b > 0) * (test_strip_img_b < 1)).astype(np.int)) <= 0
    test_strip_img_a = image_transform(test_strip_img_a)[None, ...]
    test_strip_img_b = image_transform(test_strip_img_b)[None, ...]
    # Re-binarize after the resize.
    test_strip_img_a = (test_strip_img_a > 0.5).float()
    test_strip_img_b = (test_strip_img_b > 0.5).float()
    print('Test strip stats: ', torch.mean(test_strip_img_a), torch.min(test_strip_img_a), torch.max(test_strip_img_a))
    print('Test strip stats: ', torch.mean(test_strip_img_b), torch.min(test_strip_img_b), torch.max(test_strip_img_b))

    for em_step, (img_hat_em, em_field) in enumerate(model(img, summary_writer=None, train_step=0)):
        print(img_name, '\tem step: ', em_step, em_steps, end='\r')
        
        # Save the em field and energy at the target step.
        e_field_img = em_field[0:3,...]
        h_field_img = em_field[3:6,...]
        
        #if(em_step == argmax_step):
        #if(em_step % 10 == 0):
        if(True):
            masked_output_a = test_strip_img_a * torch.unsqueeze(img_hat_em, 0)
            masked_output_b = test_strip_img_b * torch.unsqueeze(img_hat_em, 0)
            masked_output_a = torch.squeeze(masked_output_a)
            masked_output_b = torch.squeeze(masked_output_b)
            masked_output_a = torch.sum(masked_output_a, axis=-2)
            masked_output_b = torch.sum(masked_output_b, axis=-2)
            # Sum the input image over the y dimension.
            input_img_masked_sum = test_strip_img_a * img
            input_img_masked_sum = torch.squeeze(input_img_masked_sum)
            print(test_strip_img_a.shape, input_img_masked_sum.shape)
            input_img_masked_sum = torch.sum(input_img_masked_sum, axis=-2)
            
            print(test_strip_img_a.shape, input_img_masked_sum.shape)
            print(test_strip_img_a.shape, input_img_masked_sum.shape)
            
        fig = Figure(figsize=(4.8, 4.8), dpi=100)
        fig.tight_layout(pad=0)
        canvas = FigureCanvasAgg(fig)
        # Do some plotting here
        ax = fig.add_subplot(111)
        ax.plot(masked_output_a.detach().numpy())
        ax.plot(input_img_masked_sum.detach().numpy())
        #ax.plot([1, 2, 3])
        # Retrieve a view on the renderer buffer
        canvas.draw()
        buf = canvas.buffer_rgba()
        # convert to a NumPy array
        plot_img = torch.from_numpy(np.transpose(np.asarray(buf).astype(np.float32), (2,0,1))[0:3, ...])/255.0
        
            #plt.show()
        # Add the argmaxxed images to tensorboard
        if(args.grayscale):
            img_save =  scale_img(img.expand(-1, 3, -1, -1), s=3)
            #img_hat_em_save =  img_hat_em_save.expand(3, -1, -1)
            img_hat_em_save =  scale_img(img_hat_em, s=3).expand(3, -1, -1)
            test_strip_img_a_save = scale_img(test_strip_img_a, s=3).expand(-1, 3, -1, -1)[0]
            masked_output_a_save = scale_img(test_strip_img_a * torch.unsqueeze(img_hat_em, 0), s=3).expand(-1, 3, -1, -1)[0]
        img_grid = torchvision.utils.make_grid([img_save[0,...], img_hat_em_save, masked_output_a_save, plot_img,
            util.norm_img_by_chan(scale_img(e_field_img, s=3)), 
            util.norm_img_by_chan(scale_img(h_field_img, s=3))], nrow=3, pad_value=4)
        save_image(img_grid, './images/{0}_step_{1}.png'.format(img_name, str(em_step).zfill(12)))
        
    print('')
    


Processing:  robinson_3
Opening image ./optical_illusions/robinson_3.png with test strip file ./optical_illusions/test_strips/robinson_3_teststrip_part_a.png
Could not find ./optical_illusions/test_strips/robinson_3_teststrip_part_b.png, making zeros.
Test strip stats:  tensor(0.0750, dtype=torch.float32) tensor(0., dtype=torch.float32) tensor(1., dtype=torch.float32)
Test strip stats:  tensor(0., dtype=torch.float32) tensor(0., dtype=torch.float32) tensor(0., dtype=torch.float32)
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])


/tmp/ipykernel_7076/635249257.py:40: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  assert np.sum(((test_strip_img_a > 0) * (test_strip_img_a < 1)).astype(np.int)) <= 0
/tmp/ipykernel_7076/635249257.py:41: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for a

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 160]) torch.Size([160, 160])
torch.Size([1, 1, 160, 160]) torch.Size([160])
torch.Size([1, 1, 160, 16

# Test slicing


In [1]:
import numpy as np
import torch 
x = torch.arange(10)

In [4]:
torch.roll(x, -1, 0)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
x[1:]

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[:-1]

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
 print(x[1:, :, :, 1] - x[:-1, :, :, 1])
 print(x[:, 1:, :, 0] - x[:, :-1, :, 0])


[[[300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]]

 [[300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]]

 [[300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 300 300 300 300]
  [300 300 300 300 300 300 3

In [11]:
x = np.arange(10*10*10*3).reshape(10, 10, 10, 3)

In [33]:
np.roll(x[..., 1], -1, 0)

array([[[ 301,  304,  307,  310,  313,  316,  319,  322,  325,  328],
        [ 331,  334,  337,  340,  343,  346,  349,  352,  355,  358],
        [ 361,  364,  367,  370,  373,  376,  379,  382,  385,  388],
        [ 391,  394,  397,  400,  403,  406,  409,  412,  415,  418],
        [ 421,  424,  427,  430,  433,  436,  439,  442,  445,  448],
        [ 451,  454,  457,  460,  463,  466,  469,  472,  475,  478],
        [ 481,  484,  487,  490,  493,  496,  499,  502,  505,  508],
        [ 511,  514,  517,  520,  523,  526,  529,  532,  535,  538],
        [ 541,  544,  547,  550,  553,  556,  559,  562,  565,  568],
        [ 571,  574,  577,  580,  583,  586,  589,  592,  595,  598]],

       [[ 601,  604,  607,  610,  613,  616,  619,  622,  625,  628],
        [ 631,  634,  637,  640,  643,  646,  649,  652,  655,  658],
        [ 661,  664,  667,  670,  673,  676,  679,  682,  685,  688],
        [ 691,  694,  697,  700,  703,  706,  709,  712,  715,  718],
        [ 721,  72

In [31]:
x[1:, :, :, 1]

array([[[ 301,  304,  307,  310,  313,  316,  319,  322,  325,  328],
        [ 331,  334,  337,  340,  343,  346,  349,  352,  355,  358],
        [ 361,  364,  367,  370,  373,  376,  379,  382,  385,  388],
        [ 391,  394,  397,  400,  403,  406,  409,  412,  415,  418],
        [ 421,  424,  427,  430,  433,  436,  439,  442,  445,  448],
        [ 451,  454,  457,  460,  463,  466,  469,  472,  475,  478],
        [ 481,  484,  487,  490,  493,  496,  499,  502,  505,  508],
        [ 511,  514,  517,  520,  523,  526,  529,  532,  535,  538],
        [ 541,  544,  547,  550,  553,  556,  559,  562,  565,  568],
        [ 571,  574,  577,  580,  583,  586,  589,  592,  595,  598]],

       [[ 601,  604,  607,  610,  613,  616,  619,  622,  625,  628],
        [ 631,  634,  637,  640,  643,  646,  649,  652,  655,  658],
        [ 661,  664,  667,  670,  673,  676,  679,  682,  685,  688],
        [ 691,  694,  697,  700,  703,  706,  709,  712,  715,  718],
        [ 721,  72

In [34]:
np.roll(x[..., 1], -1, 0)

array([[[ 301,  304,  307,  310,  313,  316,  319,  322,  325,  328],
        [ 331,  334,  337,  340,  343,  346,  349,  352,  355,  358],
        [ 361,  364,  367,  370,  373,  376,  379,  382,  385,  388],
        [ 391,  394,  397,  400,  403,  406,  409,  412,  415,  418],
        [ 421,  424,  427,  430,  433,  436,  439,  442,  445,  448],
        [ 451,  454,  457,  460,  463,  466,  469,  472,  475,  478],
        [ 481,  484,  487,  490,  493,  496,  499,  502,  505,  508],
        [ 511,  514,  517,  520,  523,  526,  529,  532,  535,  538],
        [ 541,  544,  547,  550,  553,  556,  559,  562,  565,  568],
        [ 571,  574,  577,  580,  583,  586,  589,  592,  595,  598]],

       [[ 601,  604,  607,  610,  613,  616,  619,  622,  625,  628],
        [ 631,  634,  637,  640,  643,  646,  649,  652,  655,  658],
        [ 661,  664,  667,  670,  673,  676,  679,  682,  685,  688],
        [ 691,  694,  697,  700,  703,  706,  709,  712,  715,  718],
        [ 721,  72

In [36]:
x[:-1,:,:,1]

array([[[   1,    4,    7,   10,   13,   16,   19,   22,   25,   28],
        [  31,   34,   37,   40,   43,   46,   49,   52,   55,   58],
        [  61,   64,   67,   70,   73,   76,   79,   82,   85,   88],
        [  91,   94,   97,  100,  103,  106,  109,  112,  115,  118],
        [ 121,  124,  127,  130,  133,  136,  139,  142,  145,  148],
        [ 151,  154,  157,  160,  163,  166,  169,  172,  175,  178],
        [ 181,  184,  187,  190,  193,  196,  199,  202,  205,  208],
        [ 211,  214,  217,  220,  223,  226,  229,  232,  235,  238],
        [ 241,  244,  247,  250,  253,  256,  259,  262,  265,  268],
        [ 271,  274,  277,  280,  283,  286,  289,  292,  295,  298]],

       [[ 301,  304,  307,  310,  313,  316,  319,  322,  325,  328],
        [ 331,  334,  337,  340,  343,  346,  349,  352,  355,  358],
        [ 361,  364,  367,  370,  373,  376,  379,  382,  385,  388],
        [ 391,  394,  397,  400,  403,  406,  409,  412,  415,  418],
        [ 421,  42

In [40]:
np.roll(x[..., 1], +1, 0)

array([[[2701, 2704, 2707, 2710, 2713, 2716, 2719, 2722, 2725, 2728],
        [2731, 2734, 2737, 2740, 2743, 2746, 2749, 2752, 2755, 2758],
        [2761, 2764, 2767, 2770, 2773, 2776, 2779, 2782, 2785, 2788],
        [2791, 2794, 2797, 2800, 2803, 2806, 2809, 2812, 2815, 2818],
        [2821, 2824, 2827, 2830, 2833, 2836, 2839, 2842, 2845, 2848],
        [2851, 2854, 2857, 2860, 2863, 2866, 2869, 2872, 2875, 2878],
        [2881, 2884, 2887, 2890, 2893, 2896, 2899, 2902, 2905, 2908],
        [2911, 2914, 2917, 2920, 2923, 2926, 2929, 2932, 2935, 2938],
        [2941, 2944, 2947, 2950, 2953, 2956, 2959, 2962, 2965, 2968],
        [2971, 2974, 2977, 2980, 2983, 2986, 2989, 2992, 2995, 2998]],

       [[   1,    4,    7,   10,   13,   16,   19,   22,   25,   28],
        [  31,   34,   37,   40,   43,   46,   49,   52,   55,   58],
        [  61,   64,   67,   70,   73,   76,   79,   82,   85,   88],
        [  91,   94,   97,  100,  103,  106,  109,  112,  115,  118],
        [ 121,  12

In [2]:
load_grid_params_to_learn = torch.load('model_checkpoints/stability-improvements-simple/md_000000031000.grd')

In [4]:
len(load_grid_params_to_learn)

3

In [5]:
for idx,t in enumerate(load_grid_params_to_learn):
    print(idx, t.shape)

0 torch.Size([16, 2, 1, 1])
1 torch.Size([16])
2 torch.Size([122])


In [7]:
 torch.save([load_grid_params_to_learn[-1]],'model_checkpoints/stability-improvements-simple/md_000000031000.grd')